"""`shoal serve` -- run an existing app with the right topology for this build.

This is the whole Tier 1 story and it changes no application code. A WSGI app
served as 32 processes and the same app served as 1 process with 32 threads are
the same program; only the second one shares its heap. Which is correct depends
entirely on whether the GIL is off, so the decision is made here rather than
left in a deployment script written years ago.
"""
from __future__ import annotations

import os
import shutil
import sys
from dataclasses import dataclass

from ._build import Build, detect


def usable_cores() -> tuple[int, str]:
    """Cores this process may actually use -- cgroup quota before cpu_count()."""
    import os

    limits: list[tuple[int, str]] = []
    try:
        quota, period = open("/sys/fs/cgroup/cpu.max").read().split()
        if quota != "max":
            limits.append((max(1, int(int(quota) / int(period))), "cgroup v2 quota"))
    except (OSError, ValueError):
        pass
    try:
        q = int(open("/sys/fs/cgroup/cpu/cpu.cfs_quota_us").read())
        per = int(open("/sys/fs/cgroup/cpu/cpu.cfs_period_us").read())
        if q > 0:
            limits.append((max(1, q // per), "cgroup v1 quota"))
    except (OSError, ValueError):
        pass
    try:
        limits.append((len(os.sched_getaffinity(0)), "sched affinity"))
    except (AttributeError, OSError):
        pass
    pcc = getattr(os, "process_cpu_count", None)
    if pcc and pcc():
        limits.append((pcc(), "process_cpu_count"))
    if os.cpu_count():
        limits.append((os.cpu_count(), "cpu_count"))
    if not limits:
        return 1, "unknown"
    return min(limits, key=lambda x: x[0])


@dataclass(frozen=True)
class Topology:
    processes: int
    threads: int
    preload: bool            # import once in the parent, fork, share by CoW
    strategy: str            # "preforked" | "threaded"
    reason: str

    @property
    def concurrency(self) -> int:
        return self.processes * self.threads

    @property
    def shares_memory(self) -> bool:
        return self.preload or self.strategy == "threaded"


def plan(build: Build, cores: int, kind: str,
         processes: int | None = None, threads: int | None = None,
         want_shared_state: bool = False) -> Topology:
    """Decide how to run. Pure, so every branch is testable without a server.

    Measured on this project's own benchmark (see FINDINGS.md), 8 workers,
    PSS under load:

        spawned     132 MB (GIL)   233 MB (free-threaded)
        preforked    40 MB          51 MB
        threaded     18 MB          78 MB

    Pre-forking from a preloaded parent wins on both builds, which is the
    opposite of what this project originally assumed. Threads only beat it on a
    GIL build, where they cannot run in parallel and so are useless for CPU.
    Free-threading makes threads *more* expensive, not less: each one carries
    its own mimalloc arenas.
    """
    if processes is not None or threads is not None:
        p = processes if processes is not None else 1
        t = threads if threads is not None else 1
        strat = "threaded" if p == 1 and t > 1 else "preforked"
        return Topology(p, t, preload=True, strategy=strat,
                        reason="explicitly overridden (still preloading)")

    if want_shared_state:
        if build.collapse_capable:
            t = cores if kind == "asgi" else cores * 2
            return Topology(1, t, preload=True, strategy="threaded",
                            reason="one heap requested: shared caches and one "
                                   "connection pool, at higher memory than pre-fork")
        return Topology(1, max(2, cores), preload=True, strategy="threaded",
                        reason="one heap requested, but the GIL is on: these threads "
                               "share state without running in parallel")

    # The default, and the measured best on both builds.
    if build.freethreaded and build.gil_on:
        why = ("pre-fork with preload: shares the interpreter and imports by "
               "copy-on-write. (The GIL is on despite a free-threaded build, "
               "but pre-fork would win here regardless.)")
    else:
        why = ("pre-fork with preload: shares the interpreter and imports by "
               "copy-on-write, measured 70-78% below spawning workers separately")
    return Topology(cores, 1, preload=True, strategy="preforked", reason=why)


@dataclass(frozen=True)
class ServerChoice:
    name: str
    argv: list[str]
    note: str = ""


GUNICORN_CONF = '''# generated by shoal -- makes preloading actually pay off
import gc


def when_ready(server):
    """Freeze before the workers are forked.

    --preload alone is not enough. The collector's mark phase writes to the
    header of every object it visits, so copy-on-write copies those pages into
    each child and the sharing you preloaded for is gone within minutes.
    gc.freeze() moves everything imported so far into a permanent generation the
    collector never touches, and the pages stay shared for the life of the
    worker.
    """
    gc.freeze()
'''


def write_gunicorn_conf(directory: str | None = None) -> str:
    """Write the config next to the run and return its path."""
    import tempfile

    d = directory or tempfile.mkdtemp(prefix="shoal-")
    path = os.path.join(d, "shoal_gunicorn_conf.py")
    with open(path, "w") as fh:
        fh.write(GUNICORN_CONF)
    return path


def _which(*names: str) -> str | None:
    for n in names:
        if shutil.which(n):
            return n
    return None


def choose_server(kind: str, topo: Topology, target: str,
                  host: str, port: int, prefer: str | None = None) -> ServerChoice:
    """Pick an installed server and express the topology in its own flags."""
    bind = f"{host}:{port}"
    order = ([prefer] if prefer else []) + (
        ["granian", "uvicorn", "gunicorn"] if kind == "asgi"
        else ["gunicorn", "waitress", "granian"])

    for name in order:
        if name == "gunicorn" and _which("gunicorn"):
            argv = ["gunicorn", "--bind", bind,
                    "--workers", str(topo.processes),
                    "--threads", str(topo.threads)]
            note = "workers/threads map directly onto the topology"
            if topo.preload:
                argv += ["--preload", "-c", write_gunicorn_conf()]
                note += "; --preload plus gc.freeze() in when_ready"
            if kind == "asgi":
                argv += ["--worker-class", "uvicorn.workers.UvicornWorker"]
            return ServerChoice("gunicorn", argv + [target], note)

        if name == "granian" and _which("granian"):
            return ServerChoice("granian",
                                ["granian", "--interface", kind,
                                 "--host", host, "--port", str(port),
                                 "--workers", str(topo.processes),
                                 "--blocking-threads", str(topo.threads), target],
                                "Rust core; check your granian version for a preload "
                                "equivalent -- without one each worker imports separately")

        if name == "uvicorn" and _which("uvicorn"):
            return ServerChoice("uvicorn",
                                ["uvicorn", "--host", host, "--port", str(port),
                                 "--workers", str(topo.processes), target],
                                "uvicorn cannot preload: every worker imports the "
                                "application for itself. Install gunicorn to share "
                                "those pages -- it is worth 70-78%")

        if name == "waitress" and _which("waitress-serve"):
            return ServerChoice("waitress",
                                ["waitress-serve", f"--listen={bind}",
                                 f"--threads={topo.threads}", target],
                                "threads only; ignores the process count")

    return ServerChoice("", [], "no supported server found")


def render_plan(build: Build, cores: int, why: str, kind: str,
                topo: Topology, server: ServerChoice, target: str) -> str:
    L = [""]
    L.append(f"  shoal serve   {target}")
    L.append("")
    L.append(f"  {'interpreter':<14} {build.summary()}")
    L.append(f"  {'cores':<14} {cores} ({why})")
    L.append(f"  {'application':<14} {kind.upper()}")
    L.append(f"  {'strategy':<14} {topo.strategy}"
             f"{' + preload' if topo.preload else ''}")
    L.append(f"  {'topology':<14} {topo.processes} process(es) x {topo.threads} thread(s)"
             f"  = {topo.concurrency} concurrent")
    L.append(f"  {'why':<14} {topo.reason}")
    if server.name:
        L.append(f"  {'server':<14} {server.name} - {server.note}")
        L.append("")
        L.append("  " + " ".join(server.argv))
    else:
        L.append(f"  {'server':<14} none found - install gunicorn, granian, uvicorn or waitress")
    L.append("")

    if topo.preload and topo.strategy == "preforked":
        L.append("  Workers fork from a parent that has already imported the")
        L.append("  application, and gc.freeze() keeps those pages shared instead")
        L.append("  of letting the collector copy them apart. Measured at 70-78%")
        L.append("  below running the same workers without preload. See FINDINGS.md.")
        L.append("")
    elif topo.strategy == "threaded":
        L.append("  NOTE  one heap means shared caches and a single connection pool,")
        L.append("        but on measurement threads cost MORE memory than pre-fork")
        L.append("        (78 MB against 51 MB at 8 workers, free-threaded). Choose")
        L.append("        this for shared state, not to save memory.")
        L.append("")
    if not topo.preload:
        L.append("  NOTE  not preloading: every worker imports the application for")
        L.append("        itself and shares nothing. That is the most expensive way")
        L.append("        to run this, by a factor of three.")
        L.append("")
    return "\n".join(L)
